apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykubetest
  namespace: myspace
  labels:
    app: mykubetest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mykubetest
  template:
    metadata:
      labels:
        app: mykubetest
    spec:
      containers:
        - name: mykubetest
          image: localhost:32000/mykubetest:0.0.44
          ports:
            - containerPort: 80
      serviceAccountName: build-robot
      imagePullSecrets:
        - name: myregistry
